import type { ProjectMenuData } from './projectMenu.types';

export const PROJECT_CATEGORIES = {
  VIDEO_SURVEILLANCE: 'video-surveillance',
  FIRE_ALARM: 'fire-alarm',
  ACCESS_CONTROL: 'access-control',
  NOTIFICATION_SYSTEM: 'notification-system',
  FIRE_SUPPRESSION: 'fire-suppression',
  COMPLEX: 'complex',
  ALL: 'all',
} as const;

export const PROJECT_MENU_DATA: ProjectMenuData[] = [
  {
    id: 1,
    title: 'Филиал «Назарбаев Интеллектуальная школа» г. Тараз, АОО «НИШ»',
    service: 'Система видеонаблюдения',
    subtitle: 'Реализовали техническое обслуживание системы видеонаблюдения.',
    image: '/img/projectMenu/Project-1.webp',
    type: 'video-surveillance',
  },
  {
    id: 2,
    title: 'КГУ «Аппарат акима Жамбылской области»',
    subtitle:
      'Реализовали установку системы видеонаблюдения в резиденции акима Жамбылской области.',
    service: 'Система видеонаблюдения',
    image: '/img/projectMenu/Project-2.webp',
    type: 'video-surveillance',
  },
  {
    id: 3,
    title: 'ЖОФ АО «Казпочта»',
    subtitle:
      'Реализовали установку охранной сигнализации, домофонов, системы контроля доступа и тревожной сигнализации.',
    service: 'Комплексная безопасность',
    image: '/img/projectMenu/Project-3.webp',
    type: 'access-control',
  },
  {
    id: 4,
    title: 'ТОО «Фиркан»',
    subtitle: 'Реализовали монтаж системы пожарной сигнализации.',
    service: 'Пожарная сигнализация',
    image: '/img/projectMenu/Project-4.webp',
    type: 'fire-alarm',
  },
  {
    id: 5,
    title: 'ТОО «Научно-клинический центр кардиохирургии и трансплантации»',
    subtitle: 'Реализовали поставку оборудования системы безопасности для медицинского учреждения.',
    service: 'Система видеонаблюдения',
    image: '/img/projectMenu/Project-5.webp',
    type: 'video-surveillance',
  },
  {
    id: 6,
    title: 'КГП «Тараз-Арена»',
    subtitle: 'Реализовали техническое обслуживание системы видеонаблюдения.',
    service: 'Система видеонаблюдения',
    image: '/img/projectMenu/Project-6.webp',
    type: 'video-surveillance',
  },
  {
    id: 7,
    title: 'ГУ «Департамент КНБ РК по Жамбылской области»',
    subtitle:
      'Реализовали техническое обслуживание систем охранно-пожарной сигнализации и видеонаблюдения.',
    service: 'Охранно-пожарная система',
    image: '/img/projectMenu/Project-7.webp',
    type: 'fire-alarm',
  },
  {
    id: 8,
    title: 'НАО «КазНИТУ им. К.И. Сатпаева»',
    subtitle:
      'Реализовали ремонт и модернизацию пожарной и охранной сигнализации, а также систем тушения.',
    service: 'Охранно-пожарная система',
    image: '/img/projectMenu/Project-8.webp',
    type: 'fire-alarm',
  },
  {
    id: 9,
    title: 'АО «Казахский агротехнический университет им. С. Сейфуллина»',
    subtitle: 'Реализовали установку системы видеонаблюдения во всех корпусах университета.',
    service: 'Система видеонаблюдения',
    image: '/img/projectMenu/Project-9.webp',
    type: 'video-surveillance',
  },
  {
    id: 10,
    title: 'АО «Университет КИМЭП»',
    subtitle:
      'Реализовали установку системы видеонаблюдения, контроля доступа и охранной сигнализации.',
    service: 'Комплексная безопасность',
    image: '/img/projectMenu/Project-10.webp',
    type: 'complex',
  },
  {
    id: 11,
    title: 'РГУ «Казахская национальная академия искусств им. Т.К. Жургенова»',
    subtitle: 'Реализовали установку системы пожарной сигнализации.',
    service: 'Пожарная сигнализация',
    image: '/img/projectMenu/Project-11.webp',
    type: 'fire-alarm',
  },
  {
    id: 12,
    title: 'РГУ «Национальный архив Республики Казахстан»',
    subtitle: 'Реализовали установку адресной пожарной сигнализации.',
    service: 'Охранно-пожарная система',
    image: '/img/projectMenu/Project-12.webp',
    type: 'fire-alarm',
  },
  {
    id: 13,
    title: 'ГУ «Служба пожаротушения и аварийно-спасательных работ» ДЧС г. Алматы',
    subtitle: 'Реализовали установку системы видеонаблюдения.',
    service: 'Система видеонаблюдения',
    image: '/img/projectMenu/Project-13.webp',
    type: 'video-surveillance',
  },
  {
    id: 14,
    title: 'РГУ «Казахская национальная консерватория им. Курмангазы»',
    subtitle: 'Реализовали монтаж пропускной системы-турникетов в общежитии.',
    service: 'Система контроля доступа',
    image: '/img/projectMenu/Project-14.webp',
    type: 'access-control',
  },
  {
    id: 15,
    title: 'КГУ «Управление культуры города Алматы»',
    subtitle: 'Реализовали монтаж охранной сигнализации и системы видеонаблюдения.',
    service: 'Комплексная безопасность',
    image: '/img/projectMenu/Project-15.webp',
    type: 'complex',
  },
  {
    id: 16,
    title: 'ДБ АО «Банк Хоум Кредит»',
    subtitle:
      'Реализовали монтаж охранной сигнализации, системы видеонаблюдения, пожарной сигнализации, контроля доступа и газового пожаротушения в отделении г. Тараз.',
    service: 'Комплексная безопасность',
    image: '/img/projectMenu/Project-16.webp',
    type: 'complex',
  },
  {
    id: 17,
    title: 'ГУ «Министерство иностранных дел Республики Казахстан»',
    subtitle: 'Реализовали текущий ремонт системы пожарной сигнализации здания ДКС МИД РК.',
    service: 'Охранно-пожарная система',
    image: '/img/projectMenu/Project-17.webp',
    type: 'fire-alarm',
  },
  {
    id: 18,
    title: 'НАО «Евразийский национальный университет им. Л.Н. Гумилева»',
    subtitle:
      'Реализовали замену автоматической пожарной сигнализации в учебно-административном корпусе.',
    service: 'Охранно-пожарная система',
    image: '/img/projectMenu/Project-18.webp',
    type: 'fire-alarm',
  },
  {
    id: 19,
    title: 'АО «Агентство "Хабар"»',
    subtitle:
      'Реализовали монтаж системы пожарной сигнализации с заменой и установкой оборудования.',
    service: 'Охранно-пожарная система',
    image: '/img/projectMenu/Project-19.webp',
    type: 'fire-alarm',
  },
  {
    id: 20,
    title: 'НАО «КазНУ им. Аль-Фараби»',
    subtitle: 'Реализовали установку системы оповещения',
    service: 'Система оповещения',
    image: '/img/projectMenu/Project-20.webp',
    type: 'notification-system',
  },
  {
    id: 21,
    title: 'ГУ «Министерство энергетики Республики Казахстан»',
    subtitle: 'Реализовали монтаж комплексной системы безопасности.',
    service: 'Комплексная безопасность',
    image: '/img/projectMenu/Project-21.webp',
    type: 'complex',
  },
  {
    id: 22,
    title: 'АО «Отбасы Банк»',
    subtitle: 'Реализовали поставку прибора речевого оповещения.',
    service: 'Система оповещения',
    image: '/img/projectMenu/Project-22.webp',
    type: 'notification-system',
  },
  {
    id: 23,
    title: 'НАО «Таразский региональный университет им. М.Х. Дулати»',
    subtitle: 'Реализовали установку охранной сигнализации и системы видеонаблюдения.',
    service: 'Комплексная безопасность',
    image: '/img/projectMenu/Project-23.webp',
    type: 'complex',
  },
  {
    id: 24,
    title: 'РГУ «Министерство финансов Республики Казахстан»',
    subtitle:
      'Реализовали прокладку структурированной кабельной сети в УГД и ДГД различных регионов.',
    service: 'Комплексная безопасность',
    image: '/img/projectMenu/Project-24.webp',
    type: 'complex',
  },
  {
    id: 25,
    title: 'НАО «Актюбинский региональный университет им. К. Жубанова»',
    subtitle: 'Реализовали установку системы видеонаблюдения.',
    service: 'Система видеонаблюдения',
    image: '/img/projectMenu/Project-25.webp',
    type: 'video-surveillance',
  },
  {
    id: 26,
    title: 'ГУ «Департамент полиции Кызылординской области» МВД РК',
    subtitle: 'Реализовали приобретение и установку камер видеонаблюдения для служебных помещений.',
    service: 'Система видеонаблюдения',
    image: '/img/projectMenu/Project-26.webp',
    type: 'video-surveillance',
  },
  {
    id: 27,
    title: 'ТОО «Qazaq Stroy Almaty»',
    subtitle: 'Реализовали поставку оборудования комплекса систем безопасности.',
    service: 'Комплексная безопасность',
    image: '/img/projectMenu/Project-27.webp',
    type: 'complex',
  },
  {
    id: 28,
    title: 'РГУ «Департамент по делам обороны Жамбылской области» МО РК',
    subtitle: 'Реализовали установку охранной сигнализации.',
    service: 'Охранно-пожарная система',
    image: '/img/projectMenu/product-item-5.webp',
    type: 'fire-alarm',
  },
  {
    id: 29,
    title: 'КГУ «Областная спортивная школа олимпийского резерва № 5»',
    subtitle: 'Реализовали установку охранной сигнализации.',
    service: 'Охранно-пожарная система',
    image: '/img/projectMenu/product-item-5.webp',
    type: 'fire-alarm',
  },
  {
    id: 30,
    title: 'РГУ «Департамент государственных доходов по г. Нур-Султану КГД МФ РК»',
    subtitle: 'Реализовали установку системы контроля доступа.',
    service: 'Система контроля доступа',
    image: '/img/projectMenu/Project-30.webp',
    type: 'access-control',
  },
  {
    id: 31,
    title: 'РГУ «Комитет технического регулирования и метрологии МТИ РК»',
    subtitle: 'Реализовали монтажные работы системы оповещения.',
    service: 'Система оповещения',
    image: '/img/projectMenu/Project-31.webp',
    type: 'notification-system',
  },
] as const;

export const ALL_PROJECTS = [...PROJECT_MENU_DATA];

export const INITIAL_ITEMS_COUNT = 8;
