// import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
// // import './globals.css';
// import type { ReactNode } from 'react';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: ReactNode;
// }>) {
//   return (
//     <html lang="ru">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
//     </html>
//   );
// }
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import '@/styles/components/_header.scss';
import { layoutConfig } from '@/shared/config/layout.config';
import { siteConfig } from '@/shared/config/site.config';
import { Footer } from '@/widgets/footer/Footer';
import { Header } from '@/widgets/header/Header';

// import { Providers } from '@/providers/provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: siteConfig.title,
  description: siteConfig.description,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <Providers> */}
        <Header />
        <main
          className="flex flex-col items-center justify-center"
          style={{
            height: `calc(100vh - ${layoutConfig.headerHeight} - ${layoutConfig.footerHeight})`,
          }}
        >
          {children}
        </main>
        <Footer />
        {/* </Providers> */}
      </body>
    </html>
  );
}
