export type BreadcrumbWord =
  | 'services'
  | 'videonabludenie'
  | 'ops'
  | 'skd'
  | 'opoveshchenie'
  | 'pozhartushenie'
  | 'turnstiles'
  | 'switches'
  | 'servercabinets'
  | 'nvr'
  | 'cameras'
  | 'products'
  | 'itsolutionspublicprivate'
  | 'itsolutions'
  | 'workingwithntouchequipment';
